# Generated by Django 4.2.7 on 2026-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobright', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrightscraperstate',
            name='worker_pid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
